subscription_id      = "2e2b7ea8-71a7-4e33-a116-85989b5dc3b4"
resource_group_name  = "Project-Setup"
storage_account_name = "ashishlavale5tfstates"
container_name       = "roboshop-state-files"
key                  = "dev.terraform.tfstate"
